package cloud.autotests.tests;


import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static cloud.autotests.helpers.DriverHelper.getConsoleLogs;
import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Проверка работы сайта rbc.ru")
    void generatedTest() {
        step("Открыть сайт https://rbc.ru", () -> {
            open("https://rbc.ru");
        });

        step("Найти и нажать копку \"Скрыть баннеры\"", () -> {
            $x("//a[text()='Скрыть баннеры']")
                    .waitUntil(visible, 10000).click();;
        });

        step("Проверить что на открытой странице есть кнопка с текстом \"Зарегистрироваться\"", () -> {
            $x("//input[@value='Зарегистрироваться']").should(exist);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://rbc.ru'", () ->
                open("https://rbc.ru"));

        step("Page title should have text 'Новости дня в России и мире — РБК'", () -> {
            String expectedTitle = "Новости дня в России и мире — РБК";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...'")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://rbc.ru'", () ->
                open("https://rbc.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}